### ISSUE TITLE
Not generating iTAK files

### ISSUE THREAD

**Issue by Lima9092** [skadakar/taky-itak#3]
itaklink=$(curl --upload-file /root/taky-data/itak.zip https://transfer.sh/itak.zip)
curl: Can't open '/root/taky-data/itak.zip'
curl: try 'curl --help' or 'curl --manual' for more information
curl: (26) Failed to open/read local data from file/application

**Comment by Lima9092** [comment]
Started from scratch and it worked the 2nd time

**Comment by skadakar** [comment]
This is somewhat expected to happen form time to time, as this was written really fast to just get shit up and running and i couldn't be bothered writing a proper check, it simply waits 10sec and assumes that is enough. 

Re-running as you did should solve all known issues with the installer.
